package main

import (
	"bufio"
	"bytes"
	"encoding/json"
	"fmt"
	"io"
	"log"
	"net/http"
	"os"
	"regexp"
	"strconv"
	"strings"
	"time"
	"unicode/utf8"

	"github.com/prometheus/client_golang/prometheus"
	"github.com/prometheus/client_golang/prometheus/promhttp"
)

// Prometheus metric definitions (counters, histograms, gauges)
var (
	promptTokens = prometheus.NewCounterVec(
		prometheus.CounterOpts{
			Name: "ollama_prompt_tokens_total",
			Help: "Total number of prompt tokens sent to the model",
		},
		[]string{"model"},
	)
	generatedTokens = prometheus.NewCounterVec(
		prometheus.CounterOpts{
			Name: "ollama_generated_tokens_total",
			Help: "Total number of tokens generated by the model",
		},
		[]string{"model"},
	)
	requestDuration = prometheus.NewHistogramVec(
		prometheus.HistogramOpts{
			Name: "ollama_request_duration_seconds",
			Help: "Duration of Ollama requests in seconds",
			// Buckets for 0.1s to 60s
			Buckets: []float64{0.1, 0.5, 1, 2, 5, 10, 30, 60},
		},
		// "api_endpoint" rather than "endpoint": the Prometheus Operator stamps
		// its own endpoint="<service port name>" label on every scraped series,
		// which would collide and get this one renamed to "exported_endpoint".
		[]string{"api_endpoint", "model"},
	)
	timePerToken = prometheus.NewHistogramVec(
		prometheus.HistogramOpts{
			Name:    "ollama_time_per_token_seconds",
			Help:    "Time per generated token (seconds per token)",
			Buckets: []float64{0.01, 0.05, 0.1, 0.2, 0.5, 1, 2},
		},
		[]string{"model"},
	)
	timeToFirstToken = prometheus.NewHistogramVec(
		prometheus.HistogramOpts{
			Name:    "ollama_time_to_first_token_seconds",
			Help:    "Time from request arrival to the first streamed content token (streaming requests only)",
			Buckets: []float64{0.1, 0.25, 0.5, 1, 2.5, 5, 10, 30, 60, 120},
		},
		[]string{"api_endpoint", "model"},
	)
	loadedModelsGauge = prometheus.NewGauge(
		prometheus.GaugeOpts{
			Name: "ollama_loaded_models",
			Help: "Number of models currently loaded in memory in Ollama",
		},
	)
	loadedModelInfo = prometheus.NewGaugeVec(
		prometheus.GaugeOpts{
			Name: "ollama_model_loaded",
			Help: "Indicator (1/0) if a model is loaded in memory",
		},
		[]string{"model"},
	)
	modelRAMUsage = prometheus.NewGaugeVec(
		prometheus.GaugeOpts{
			Name: "ollama_model_ram_mb",
			Help: "RAM usage in megabytes for each loaded model",
		},
		[]string{"model"},
	)
)

func init() {
	// Register metrics with Prometheus default registry
	prometheus.MustRegister(promptTokens, generatedTokens, requestDuration, timePerToken, timeToFirstToken, loadedModelsGauge, loadedModelInfo, modelRAMUsage)
}

// Structs to parse JSON responses from Ollama
type generateResponse struct {
	Model    string `json:"model"`
	Done     *bool  `json:"done,omitempty"`
	Response string `json:"response,omitempty"`
	Message  *struct {
		Content string `json:"content"`
	} `json:"message,omitempty"`
	PromptEvalCount    *int        `json:"prompt_eval_count,omitempty"`
	EvalCount          *int        `json:"eval_count,omitempty"`
	TotalDuration      *int64      `json:"total_duration,omitempty"`
	EvalDuration       *int64      `json:"eval_duration,omitempty"`
	PromptEvalDuration *int64      `json:"prompt_eval_duration,omitempty"`
	DoneReason         interface{} `json:"done_reason,omitempty"`
}

// hasContent reports whether this chunk carried generated text, for either the
// /api/generate ("response") or /api/chat ("message.content") shape.
func (r *generateResponse) hasContent() bool {
	if r.Response != "" {
		return true
	}
	return r.Message != nil && r.Message.Content != ""
}

type psResponse struct {
	Models []struct {
		Name      string `json:"name"`
		ID        string `json:"id"`
		Size      int64  `json:"size"` // Size in bytes
		Processor string `json:"processor"`
		Until     string `json:"until"`
	} `json:"models"`
}

type modelsResponse struct {
	Models []struct {
		Name    string `json:"name"`
		Model   string `json:"model"`
		Size    int64  `json:"size"`
		Digest  string `json:"digest"`
		Details struct {
			ParentModel       string   `json:"parent_model"`
			Format            string   `json:"format"`
			Family            string   `json:"family"`
			Families          []string `json:"families"`
			ParameterSize     string   `json:"parameter_size"`
			QuantizationLevel string   `json:"quantization_level"`
		} `json:"details"`
		ExpiresAt string `json:"expires_at"`
		SizeVRAM  int64  `json:"size_vram"`
	} `json:"models"`
}

type openAIUsage struct {
	PromptTokens     int `json:"prompt_tokens"`
	CompletionTokens int `json:"completion_tokens"`
	TotalTokens      int `json:"total_tokens"`
}

// openAIResponse covers the OpenAI-compatible shapes served on /v1: the whole
// body of a non-streaming response, and a single "data:" event of a streamed
// one. The three content fields are the streamed chat delta, the streamed
// /v1/completions text, and the non-streaming chat message respectively.
type openAIResponse struct {
	Model   string       `json:"model"`
	Usage   *openAIUsage `json:"usage"`
	Choices []struct {
		Delta struct {
			Content string `json:"content"`
		} `json:"delta"`
		Text    string `json:"text"`
		Message struct {
			Content string `json:"content"`
		} `json:"message"`
	} `json:"choices"`
}

func (r *openAIResponse) hasContent() bool {
	for _, c := range r.Choices {
		if c.Delta.Content != "" || c.Text != "" || c.Message.Content != "" {
			return true
		}
	}
	return false
}

var upstreamClient = &http.Client{
	// No global timeout; model inference may take a long time
	Timeout: 0,
}

// debugModeEnabled reports whether request and response bodies should be
// logged. The value is read when handling a request so tests and long-running
// processes can change DEBUG_MODE without restarting the sidecar.
func debugModeEnabled() bool {
	enabled, err := strconv.ParseBool(os.Getenv("DEBUG_MODE"))
	return err == nil && enabled
}

func logDebugBody(direction, method, path string, body []byte) {
	if debugModeEnabled() {
		log.Printf("DEBUG %s %s %s body=%q", direction, method, path, body)
	}
}

// isOpenAICompletionPath reports whether a path is one of the OpenAI-compatible
// completion endpoints, which report token usage differently from native /api.
func isOpenAICompletionPath(path string) bool {
	return path == "/v1/chat/completions" || path == "/v1/completions"
}

// requestHeaderBlocklist are headers we must not copy onto the upstream request.
// Content-Length would be stale once we rewrite the body to inject
// stream_options; Accept-Encoding would disable Go's transparent gzip
// decompression and leave us parsing compressed bytes. The rest are hop-by-hop.
var requestHeaderBlocklist = map[string]bool{
	"host":              true,
	"content-length":    true,
	"accept-encoding":   true,
	"connection":        true,
	"keep-alive":        true,
	"transfer-encoding": true,
	"te":                true,
	"trailer":           true,
}

// fixDoneReason processes JSON data to handle the done_reason field that might be a number or string
func fixDoneReason(data []byte) []byte {
	re := regexp.MustCompile(`"done_reason":(\d+)`)
	return re.ReplaceAll(data, []byte(`"done_reason":"$1"`))
}

// sanitizeUTF8 replaces invalid UTF-8 byte sequences with U+FFFD.
//
// A model can emit a broken multi-byte sequence, and downstream that is not a
// cosmetic problem: Sympozium's agent-runner ships the reply to its controller
// over gRPC, protobuf refuses to marshal a string field that is not valid UTF-8,
// and the whole result is dropped while the run still reports success. One
// corrupt byte costs the entire report. Replacing it costs one character.
//
// Doing this per line is safe because both response dialects are newline
// framed - NDJSON for /api/*, SSE for /v1/* - and a newline (0x0A) can never
// appear inside a multi-byte sequence, whose bytes are all >= 0x80. So a line
// boundary never splits a character, and sanitizing a line in isolation cannot
// corrupt one that merely spans two reads.
//
// The utf8.Valid check is the fast path: the overwhelming majority of lines are
// already valid and are returned untouched, without allocating.
func sanitizeUTF8(line []byte) []byte {
	if utf8.Valid(line) {
		return line
	}
	return bytes.ToValidUTF8(line, []byte("\uFFFD"))
}

// ensureModelTag adds ":latest" to model names that don't have a tag
func ensureModelTag(modelName string) string {
	if modelName == "" {
		return modelName
	}
	if !strings.Contains(modelName, ":") {
		return modelName + ":latest"
	}
	return modelName
}

// endpointLabel turns a request path into a metric label value: "/api/chat" ->
// "chat", "/v1/chat/completions" -> "v1/chat/completions".
func endpointLabel(path string) string {
	if trimmed := strings.TrimPrefix(path, "/api/"); trimmed != path {
		return trimmed
	}
	if trimmed := strings.TrimPrefix(path, "/"); trimmed != "" {
		return trimmed
	}
	return path
}

// parseRequestJSON decodes a JSON request body, keeping numbers as json.Number
// so the body can be re-marshalled without mangling integer literals.
func parseRequestJSON(body []byte) map[string]interface{} {
	if len(body) == 0 {
		return nil
	}
	dec := json.NewDecoder(bytes.NewReader(body))
	dec.UseNumber()
	var parsed map[string]interface{}
	if err := dec.Decode(&parsed); err != nil {
		return nil
	}
	var extra interface{}
	if err := dec.Decode(&extra); err != io.EOF {
		return nil
	}
	return parsed
}

// parseRequestValues reads one process-wide JSON request configuration value.
func parseRequestValues(envVar string) (map[string]interface{}, error) {
	raw := os.Getenv(envVar)
	if raw == "" {
		return map[string]interface{}{}, nil
	}
	parsed := parseRequestJSON([]byte(raw))
	if parsed == nil {
		return nil, fmt.Errorf("%s must be a valid JSON object", envVar)
	}
	return parsed, nil
}

// parseRequestOverrides reads values that always win over client values.
func parseRequestOverrides() (map[string]interface{}, error) {
	return parseRequestValues("OLLAMA_PROXY_REQUEST_OVERRIDES")
}

// parseRequestDefaults reads values that are only used when the client omitted
// them, allowing clients to opt out by supplying their own value.
func parseRequestDefaults() (map[string]interface{}, error) {
	return parseRequestValues("OLLAMA_PROXY_REQUEST_DEFAULTS")
}

// sanitizeUTF8ResponsesEnabled reports whether invalid UTF-8 in upstream
// responses should be repaired. It defaults to true so broken model output
// cannot make downstream protobuf/gRPC messages unmarshalable, and an
// unparseable value keeps that default rather than silently switching the
// protection off: disabling it is a deliberate choice, never a typo.
func sanitizeUTF8ResponsesEnabled() bool {
	raw := os.Getenv("OLLAMA_SANITIZE_UTF8_RESPONSE")
	if raw == "" {
		return true
	}
	enabled, err := strconv.ParseBool(raw)
	if err != nil {
		log.Printf("WARNING: ignoring unparseable OLLAMA_SANITIZE_UTF8_RESPONSE=%q; keeping sanitization enabled", raw)
		return true
	}
	return enabled
}

// promoteReasoningToContentEnabled reports whether an assistant message that
// carries reasoning but no content should have the reasoning promoted into
// content. It defaults to true for the same reason UTF-8 repair does: the
// alternative is the caller receiving nothing at all. An unparseable value
// keeps the default rather than silently switching the repair off.
func promoteReasoningToContentEnabled() bool {
	raw := os.Getenv("OLLAMA_PROMOTE_REASONING_TO_CONTENT")
	if raw == "" {
		return true
	}
	enabled, err := strconv.ParseBool(raw)
	if err != nil {
		log.Printf("WARNING: ignoring unparseable OLLAMA_PROMOTE_REASONING_TO_CONTENT=%q; keeping promotion enabled", raw)
		return true
	}
	return enabled
}

// promoteReasoningToContent rewrites a non-streaming /v1 chat completion whose
// assistant message has empty content but non-empty reasoning, copying the
// reasoning into content. It returns the body to send and how many choices it
// rewrote.
//
// A thinking model routinely spends its final turn entirely in `reasoning` and
// leaves `content` empty. A client reading only `content` then gets a
// successful, well-formed response carrying nothing and reports no error - the
// answer was produced and thrown away. Delivering it is strictly better.
//
// Two guards keep this off a healthy response. A choice carrying `tool_calls`
// is legitimately content-empty - that is a tool-call turn, not a lost answer -
// and is left alone. And `reasoning` is copied rather than moved, so a client
// reading both fields still sees exactly what the model sent.
func promoteReasoningToContent(body []byte) ([]byte, int) {
	parsed := parseRequestJSON(body)
	if parsed == nil {
		return body, 0
	}
	choices, ok := parsed["choices"].([]interface{})
	if !ok {
		return body, 0
	}
	promoted := 0
	for _, choice := range choices {
		entry, ok := choice.(map[string]interface{})
		if !ok {
			continue
		}
		msg, ok := entry["message"].(map[string]interface{})
		if !ok {
			continue
		}
		if calls, ok := msg["tool_calls"].([]interface{}); ok && len(calls) > 0 {
			continue
		}
		if content, _ := msg["content"].(string); strings.TrimSpace(content) != "" {
			continue
		}
		reasoning, _ := msg["reasoning"].(string)
		if strings.TrimSpace(reasoning) == "" {
			continue
		}
		msg["content"] = reasoning
		promoted++
	}
	if promoted == 0 {
		return body, 0
	}
	rewritten, err := json.Marshal(parsed)
	if err != nil {
		log.Printf("WARNING: could not promote reasoning to content: %v", err)
		return body, 0
	}
	return rewritten, promoted
}

// applyRequestOverrides merges defaults under client values and overrides over
// them, while preserving json.Number values when the rewritten body is
// marshalled.
func applyRequestOverrides(reqJSON, defaults, overrides map[string]interface{}) ([]byte, error) {
	merged := make(map[string]interface{}, len(reqJSON)+len(defaults)+len(overrides))
	for key, value := range defaults {
		merged[key] = value
	}
	for key, value := range reqJSON {
		merged[key] = value
	}
	for key, value := range overrides {
		merged[key] = value
	}
	return json.Marshal(merged)
}

// injectIncludeUsage rewrites a streaming /v1 request body to ask for token
// usage, which Ollama otherwise never sends. It returns the body to forward and
// whether the injection happened; a client that already set
// stream_options.include_usage is forwarded untouched so its own final usage
// chunk reaches it.
func injectIncludeUsage(reqJSON map[string]interface{}, body []byte) ([]byte, bool) {
	if reqJSON == nil {
		return body, false
	}
	if stream, _ := reqJSON["stream"].(bool); !stream {
		return body, false
	}
	opts, _ := reqJSON["stream_options"].(map[string]interface{})
	if include, _ := opts["include_usage"].(bool); include {
		return body, false
	}
	if opts == nil {
		opts = map[string]interface{}{}
	}
	opts["include_usage"] = true
	reqJSON["stream_options"] = opts
	rewritten, err := json.Marshal(reqJSON)
	if err != nil {
		log.Printf("WARNING: could not inject stream_options.include_usage: %v", err)
		return body, false
	}
	return rewritten, true
}

// requestStats accumulates what the metric updates need, whichever API dialect
// the request used.
type requestStats struct {
	start          time.Time
	streaming      bool
	model          string
	promptCount    int
	generatedCount int
	evalDurationNs int64 // native /api dialect only; reported by Ollama
	firstToken     time.Time
	lastToken      time.Time
}

// markToken records the arrival of a chunk carrying generated text, bounding the
// generation window.
func (s *requestStats) markToken() {
	now := time.Now()
	if s.firstToken.IsZero() {
		s.firstToken = now
	}
	s.lastToken = now
}

// observeOpenAIUsage picks up the model name and token counts from a /v1 body or
// stream event.
func (s *requestStats) observeOpenAIUsage(res *openAIResponse) {
	if res.Model != "" {
		s.model = ensureModelTag(res.Model)
	}
	if res.Usage != nil {
		s.promptCount = res.Usage.PromptTokens
		s.generatedCount = res.Usage.CompletionTokens
	}
}

// anthropicUsage is the usage object of the Anthropic Messages dialect.
// input_tokens excludes cached tokens, so the prompt is the sum of all three.
type anthropicUsage struct {
	InputTokens              int `json:"input_tokens"`
	CacheReadInputTokens     int `json:"cache_read_input_tokens"`
	CacheCreationInputTokens int `json:"cache_creation_input_tokens"`
	OutputTokens             int `json:"output_tokens"`
}

// anthropicEvent covers a /v1/messages body and each of its stream events:
// a body carries model and usage at the top, message_start inside "message",
// and message_delta carries the final usage at the top.
type anthropicEvent struct {
	Type    string          `json:"type"`
	Model   string          `json:"model"`
	Usage   *anthropicUsage `json:"usage"`
	Message *struct {
		Model string          `json:"model"`
		Usage *anthropicUsage `json:"usage"`
	} `json:"message"`
}

// observeAnthropic picks up the model name and token counts from a
// /v1/messages body or stream event. Later events win, but only with non-zero
// values: message_start announces a placeholder input count that Ollama
// corrects in message_delta, while Anthropic's own message_delta omits input.
func (s *requestStats) observeAnthropic(ev *anthropicEvent) {
	usage := ev.Usage
	if ev.Message != nil {
		if ev.Message.Model != "" {
			s.model = ensureModelTag(ev.Message.Model)
		}
		if usage == nil {
			usage = ev.Message.Usage
		}
	}
	if ev.Model != "" {
		s.model = ensureModelTag(ev.Model)
	}
	if usage == nil {
		return
	}
	if p := usage.InputTokens + usage.CacheReadInputTokens + usage.CacheCreationInputTokens; p > 0 {
		s.promptCount = p
	}
	if usage.OutputTokens > 0 {
		s.generatedCount = usage.OutputTokens
	}
}

// record emits the metrics for a finished request.
func (s *requestStats) record(path string) {
	if s.model == "" {
		return
	}
	if s.promptCount > 0 {
		promptTokens.WithLabelValues(s.model).Add(float64(s.promptCount))
	}
	if s.generatedCount > 0 {
		generatedTokens.WithLabelValues(s.model).Add(float64(s.generatedCount))
	}
	endpoint := endpointLabel(path)
	requestDuration.WithLabelValues(endpoint, s.model).Observe(time.Since(s.start).Seconds())
	if s.streaming && !s.firstToken.IsZero() {
		timeToFirstToken.WithLabelValues(endpoint, s.model).Observe(s.firstToken.Sub(s.start).Seconds())
	}
	switch {
	case s.generatedCount > 0 && s.evalDurationNs > 0:
		// Native dialect: Ollama reports generation time directly.
		timePerToken.WithLabelValues(s.model).Observe(float64(s.evalDurationNs) / 1e9 / float64(s.generatedCount))
	case s.streaming && s.generatedCount > 1 && s.lastToken.After(s.firstToken):
		// /v1 gives no timings, so measure the generation window (first content
		// chunk to last) ourselves. Total request duration would be dominated by
		// prompt evaluation on large contexts and badly skew the metric, so for
		// non-streaming /v1 we record nothing rather than a wrong number.
		window := s.lastToken.Sub(s.firstToken).Seconds()
		timePerToken.WithLabelValues(s.model).Observe(window / float64(s.generatedCount-1))
	}
}

// sseData returns the payload of an SSE "data:" line.
func sseData(line []byte) ([]byte, bool) {
	trimmed := bytes.TrimSpace(line)
	if !bytes.HasPrefix(trimmed, []byte("data:")) {
		return nil, false
	}
	return bytes.TrimSpace(trimmed[len("data:"):]), true
}

// refreshModelMetrics updates the loaded-model gauges from an /api/ps payload.
func refreshModelMetrics(data []byte) (int, error) {
	var ps psResponse
	if err := json.Unmarshal(data, &ps); err != nil {
		return 0, err
	}
	loadedModelsGauge.Set(float64(len(ps.Models)))
	loadedModelInfo.Reset()
	modelRAMUsage.Reset() // Reset RAM usage before updating
	for _, m := range ps.Models {
		modelName := ensureModelTag(m.Name)
		loadedModelInfo.WithLabelValues(modelName).Set(1)
		// Convert size from bytes to megabytes
		modelRAMUsage.WithLabelValues(modelName).Set(float64(m.Size) / (1024 * 1024))
	}
	return len(ps.Models), nil
}

// streamNative forwards a native /api/generate or /api/chat response chunk by
// chunk, buffering it for the token accounting done once the stream ends.
func streamNative(w http.ResponseWriter, body io.Reader, st *requestStats, sanitizeUTF8Responses bool, method, path string) bytes.Buffer {
	var buf bytes.Buffer
	flusher, _ := w.(http.Flusher)
	reader := bufio.NewReader(body)
	for {
		// NDJSON: one JSON object per line, so line-wise forwarding reproduces
		// the upstream bytes exactly, save for invalid UTF-8 - see sanitizeUTF8
		// for why that is repaired here and why per-line is safe.
		line, readErr := reader.ReadBytes('\n')
		if len(line) > 0 {
			if sanitizeUTF8Responses {
				line = sanitizeUTF8(line)
			}
			buf.Write(line)
			logDebugBody("output", method, path, line)
			if _, writeErr := w.Write(line); writeErr != nil {
				log.Printf("WARNING: client write error: %v", writeErr)
				break
			}
			if flusher != nil {
				flusher.Flush() // flush chunk to client
			}
			// Time to first token can only be seen as the chunk goes past; the
			// token counts are parsed from the whole buffer below.
			if st.streaming && st.firstToken.IsZero() {
				var res generateResponse
				if json.Unmarshal(line, &res) == nil && res.hasContent() {
					st.markToken()
				}
			}
		}
		if readErr != nil {
			// Break on EOF or error
			if readErr != io.EOF {
				log.Printf("ERROR reading upstream: %v", readErr)
			}
			break
		}
	}
	return buf
}

// streamOpenAI forwards a /v1 SSE response event by event, collecting token
// usage on the way. When dropInjectedUsage is set the usage event we asked for
// on the client's behalf is withheld, so client-visible output is unchanged.
func streamOpenAI(w http.ResponseWriter, body io.Reader, st *requestStats, dropInjectedUsage, sanitizeUTF8Responses bool, method, path string) {
	relaySSE(w, body, sanitizeUTF8Responses, method, path, func(data []byte) bool {
		if bytes.Equal(data, []byte("[DONE]")) {
			return true
		}
		var chunk openAIResponse
		if json.Unmarshal(data, &chunk) != nil {
			return true
		}
		st.observeOpenAIUsage(&chunk)
		if chunk.hasContent() {
			st.markToken()
		}
		// Ollama sends usage in a final event with no choices.
		return !(dropInjectedUsage && chunk.Usage != nil && len(chunk.Choices) == 0)
	})
}

// streamAnthropic forwards a /v1/messages SSE response untouched, collecting
// the model and token usage from its events on the way.
func streamAnthropic(w http.ResponseWriter, body io.Reader, st *requestStats, sanitizeUTF8Responses bool, method, path string) {
	relaySSE(w, body, sanitizeUTF8Responses, method, path, func(data []byte) bool {
		var ev anthropicEvent
		if json.Unmarshal(data, &ev) == nil {
			st.observeAnthropic(&ev)
			if ev.Type == "content_block_delta" {
				st.markToken()
			}
		}
		return true
	})
}

// relaySSE forwards an SSE stream line by line, flushing each one, and hands
// every data payload to onData, which returns false to withhold that event
// (its data line and the blank line ending it) from the client.
func relaySSE(w http.ResponseWriter, body io.Reader, sanitizeUTF8Responses bool, method, path string, onData func(data []byte) bool) {
	flusher, _ := w.(http.Flusher)
	reader := bufio.NewReader(body)
	pendingBlank := false // the blank line terminating a withheld event
	for {
		line, readErr := reader.ReadBytes('\n')
		if len(line) > 0 {
			if sanitizeUTF8Responses {
				line = sanitizeUTF8(line)
			}
			// Log every upstream line, including events withheld from the client.
			logDebugBody("output", method, path, line)
			forward := true
			switch data, isData := sseData(line); {
			case isData:
				forward = onData(data)
				pendingBlank = !forward
			case pendingBlank && len(bytes.TrimSpace(line)) == 0:
				forward = false
				pendingBlank = false
			default:
				pendingBlank = false
			}
			if forward {
				if _, writeErr := w.Write(line); writeErr != nil {
					log.Printf("WARNING: client write error: %v", writeErr)
					break
				}
				if flusher != nil {
					flusher.Flush()
				}
			}
		}
		if readErr != nil {
			if readErr != io.EOF {
				log.Printf("ERROR reading upstream: %v", readErr)
			}
			break
		}
	}
}

// proxyConfig carries the process-wide switches the handler needs. It is a
// struct rather than a longer parameter list because the switches are all
// bools of the same type: positional bools at a call site say nothing about
// which repair they turn off.
type proxyConfig struct {
	requestDefaults       map[string]interface{}
	requestOverrides      map[string]interface{}
	sanitizeUTF8Responses bool
	promoteReasoning      bool
}

// newMuxWithConfig builds the sidecar's handlers: /metrics, and a proxy for
// everything else that forwards to upstreamAddr while accounting for token usage.
func newMuxWithConfig(upstreamAddr string, cfg proxyConfig) *http.ServeMux {
	mux := http.NewServeMux()

	// Custom metrics handler that refreshes model data before serving metrics
	mux.HandleFunc("/metrics", func(w http.ResponseWriter, r *http.Request) {
		// Refresh model information from /api/ps before serving metrics
		if resp, err := upstreamClient.Get(upstreamAddr + "/api/ps"); err == nil {
			data, _ := io.ReadAll(resp.Body)
			resp.Body.Close()
			if count, jsonErr := refreshModelMetrics(data); jsonErr == nil {
				log.Printf("Refreshed metrics data: %d models loaded", count)
			} else {
				log.Printf("ERROR parsing /api/ps response during metrics refresh: %v", jsonErr)
			}
		} else {
			log.Printf("ERROR refreshing model metrics: %v", err)
		}

		// Serve metrics using the standard Prometheus handler
		promhttp.Handler().ServeHTTP(w, r)
	})

	// All other paths -> proxy handler
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		st := &requestStats{start: time.Now()}

		// Read request body (if any) for forwarding and to inspect the model and
		// streaming parameters
		var bodyBytes []byte
		if r.Body != nil {
			bodyBytes, _ = io.ReadAll(r.Body)
			r.Body.Close()
		}
		logDebugBody("input", r.Method, r.URL.Path, bodyBytes)
		reqJSON := parseRequestJSON(bodyBytes)

		openAIPath := isOpenAICompletionPath(r.URL.Path)
		nativeGenerate := r.URL.Path == "/api/generate" || r.URL.Path == "/api/chat"

		forwardBody := bodyBytes
		injectedUsage := false
		if r.Method == http.MethodPost && r.URL.Path == "/v1/chat/completions" {
			if reqJSON == nil {
				http.Error(w, "malformed JSON request body", http.StatusBadRequest)
				return
			}
			var rewriteErr error
			forwardBody, rewriteErr = applyRequestOverrides(reqJSON, cfg.requestDefaults, cfg.requestOverrides)
			if rewriteErr != nil {
				http.Error(w, "could not rewrite JSON request body", http.StatusBadRequest)
				return
			}
			reqJSON = parseRequestJSON(forwardBody)
		}
		if openAIPath {
			forwardBody, injectedUsage = injectIncludeUsage(reqJSON, forwardBody)
		} else if nativeGenerate {
			// Native endpoints stream unless the client opts out.
			st.streaming = true
			if stream, ok := reqJSON["stream"].(bool); ok {
				st.streaming = stream
			}
		}

		// Build upstream request
		targetURL := upstreamAddr + r.URL.Path
		if r.URL.RawQuery != "" {
			targetURL += "?" + r.URL.RawQuery
		}
		reqUp, err := http.NewRequest(r.Method, targetURL, bytes.NewReader(forwardBody))
		if err != nil {
			http.Error(w, "Bad request", http.StatusInternalServerError)
			log.Printf("ERROR creating upstream request: %v", err)
			return
		}
		// Copy original headers, minus the ones a proxy must regenerate
		for name, vals := range r.Header {
			if requestHeaderBlocklist[strings.ToLower(name)] {
				continue
			}
			for _, v := range vals {
				reqUp.Header.Add(name, v)
			}
		}
		if reqUp.Header.Get("Content-Type") == "" && len(forwardBody) > 0 {
			reqUp.Header.Set("Content-Type", "application/json")
		}

		respUp, err := upstreamClient.Do(reqUp)
		if err != nil {
			http.Error(w, "Upstream error", http.StatusBadGateway)
			log.Printf("ERROR forwarding to upstream: %v", err)
			return
		}
		defer respUp.Body.Close()

		// Forward status code and headers (except hop-by-hop headers)
		for name, vals := range respUp.Header {
			switch strings.ToLower(name) {
			case "transfer-encoding", "content-length":
				continue
			}
			for _, v := range vals {
				w.Header().Add(name, v)
			}
		}
		w.WriteHeader(respUp.StatusCode)

		switch {
		case nativeGenerate:
			// Handle streaming JSON response for generate/chat
			buf := streamNative(w, respUp.Body, st, cfg.sanitizeUTF8Responses, r.Method, r.URL.Path)

			// Fix the JSON before parsing
			bufData := fixDoneReason(buf.Bytes())

			// First, try to parse as models list response
			var modelsResp modelsResponse
			if err := json.Unmarshal(bufData, &modelsResp); err == nil && len(modelsResp.Models) > 0 {
				// This is a models list response, not a typical generate response
				for _, model := range modelsResp.Models {
					st.model = ensureModelTag(model.Model)
					modelRAMUsage.WithLabelValues(st.model).Set(float64(model.SizeVRAM) / (1024 * 1024))
				}
				log.Printf("Received models list response with %d models", len(modelsResp.Models))
				// No token counts for models list response
			} else {
				// Parse lines of JSON objects as standard generate responses
				for _, line := range bytes.Split(bufData, []byte{'\n'}) {
					if len(line) == 0 {
						continue
					}

					var res generateResponse
					if err := json.Unmarshal(line, &res); err != nil {
						log.Printf("WARNING: Failed to parse JSON: %v", err)
						continue
					}

					if res.Model != "" {
						st.model = ensureModelTag(res.Model)
					}

					// If this chunk signals done, capture metrics fields
					if res.Done != nil && *res.Done {
						if res.PromptEvalCount != nil {
							st.promptCount = *res.PromptEvalCount
						}
						if res.EvalCount != nil {
							st.generatedCount = *res.EvalCount
						}
						if res.EvalDuration != nil {
							st.evalDurationNs = *res.EvalDuration
						}
					}
				}
			}
		case r.URL.Path == "/api/ps":
			// Intercept /api/ps to update loaded models metrics
			bodyData, _ := io.ReadAll(respUp.Body)
			logDebugBody("output", r.Method, r.URL.Path, bodyData)
			w.Write(bodyData) // write response to client
			if count, err := refreshModelMetrics(bodyData); err == nil {
				log.Printf("Refreshed metrics data: %d models loaded", count)
			} else {
				log.Printf("ERROR parsing /api/ps response: %v", err)
			}
			// We can return here since request is fully handled
			return
		case openAIPath:
			// Trust the response, not the request, about whether this streamed:
			// an upstream error to a stream:true request is a plain JSON body.
			st.streaming = strings.HasPrefix(respUp.Header.Get("Content-Type"), "text/event-stream")
			if st.streaming {
				streamOpenAI(w, respUp.Body, st, injectedUsage, cfg.sanitizeUTF8Responses, r.Method, r.URL.Path)
			} else {
				// Non-streaming /v1 always carries a usage object.
				bodyData, _ := io.ReadAll(respUp.Body)
				if cfg.sanitizeUTF8Responses {
					bodyData = sanitizeUTF8(bodyData)
				}
				// Promote before logging and writing, so the debug log shows
				// what the client actually received. Streaming is not handled:
				// deciding that content stayed empty means holding the whole
				// stream, which would cost the chunk-by-chunk relay.
				if cfg.promoteReasoning {
					if promotedBody, n := promoteReasoningToContent(bodyData); n > 0 {
						log.Printf("promoted reasoning to empty content in %d choice(s)", n)
						bodyData = promotedBody
					}
				}
				logDebugBody("output", r.Method, r.URL.Path, bodyData)
				w.Write(bodyData)
				var res openAIResponse
				if err := json.Unmarshal(bodyData, &res); err == nil {
					st.observeOpenAIUsage(&res)
				} else {
					log.Printf("WARNING: Failed to parse %s response: %v", r.URL.Path, err)
				}
			}
		case r.URL.Path == "/v1/messages":
			// Anthropic Messages dialect: usage always arrives, streamed or not,
			// so there is nothing to inject and the response passes untouched.
			st.streaming = strings.HasPrefix(respUp.Header.Get("Content-Type"), "text/event-stream")
			if st.streaming {
				streamAnthropic(w, respUp.Body, st, cfg.sanitizeUTF8Responses, r.Method, r.URL.Path)
			} else {
				bodyData, _ := io.ReadAll(respUp.Body)
				if cfg.sanitizeUTF8Responses {
					bodyData = sanitizeUTF8(bodyData)
				}
				logDebugBody("output", r.Method, r.URL.Path, bodyData)
				w.Write(bodyData)
				var ev anthropicEvent
				if json.Unmarshal(bodyData, &ev) == nil {
					st.observeAnthropic(&ev)
				}
			}
			// An error body names no model; fall back to the request's.
			if m, ok := reqJSON["model"].(string); ok && st.model == "" {
				st.model = ensureModelTag(m)
			}
		default:
			// Other endpoints (e.g. /api/tags, /api/pull) - just copy through
			if debugModeEnabled() {
				bodyData, _ := io.ReadAll(respUp.Body)
				logDebugBody("output", r.Method, r.URL.Path, bodyData)
				_, _ = w.Write(bodyData)
			} else {
				_, _ = io.Copy(w, respUp.Body)
			}
			// Try to get model name from request (if JSON body has "model")
			if m, ok := reqJSON["model"].(string); ok {
				st.model = ensureModelTag(m)
			}
			// No token metrics for non-generate endpoints
		}

		st.record(r.URL.Path)

		// Logging
		duration := time.Since(st.start).Seconds()
		if st.model != "" && (st.promptCount > 0 || st.generatedCount > 0) {
			log.Printf("%s %s -> model=%s prompt_tokens=%d generated_tokens=%d duration=%.2fs",
				r.Method, r.URL.Path, st.model, st.promptCount, st.generatedCount, duration)
		} else {
			log.Printf("%s %s -> status=%d duration=%.2fs", r.Method, r.URL.Path, respUp.StatusCode, duration)
		}
	})

	return mux
}

// newMuxWithOverrides builds a proxy with only forceful overrides configured,
// keeping the many existing override tests readable. Production construction
// goes through newMuxWithConfig, which also carries defaults and the
// sanitization switch.
func newMuxWithOverrides(upstreamAddr string, requestOverrides map[string]interface{}) *http.ServeMux {
	return newMuxWithConfig(upstreamAddr, proxyConfig{
		requestDefaults:       map[string]interface{}{},
		requestOverrides:      requestOverrides,
		sanitizeUTF8Responses: true,
		promoteReasoning:      true,
	})
}

// newMux parses environment configuration once for direct proxy construction.
func newMux(upstreamAddr string) *http.ServeMux {
	overrides, err := parseRequestOverrides()
	if err != nil {
		panic(err)
	}
	defaults, err := parseRequestDefaults()
	if err != nil {
		panic(err)
	}
	return newMuxWithConfig(upstreamAddr, proxyConfig{
		requestDefaults:       defaults,
		requestOverrides:      overrides,
		sanitizeUTF8Responses: sanitizeUTF8ResponsesEnabled(),
		promoteReasoning:      promoteReasoningToContentEnabled(),
	})
}

func main() {
	// Configure upstream Ollama host and local port from environment
	upstreamAddr := os.Getenv("OLLAMA_HOST")
	if upstreamAddr == "" {
		upstreamAddr = "http://localhost:11434"
	}
	port := os.Getenv("PORT")
	if port == "" {
		port = "8080"
	}

	log.Printf("Starting Ollama proxy sidecar, forwarding to %s", upstreamAddr)
	log.Printf("Debug body logging enabled: %t", debugModeEnabled())
	log.Printf("Response UTF-8 sanitization enabled: %t", sanitizeUTF8ResponsesEnabled())

	// Optionally, initialize the loaded models gauge at startup
	if resp, err := upstreamClient.Get(upstreamAddr + "/api/ps"); err == nil {
		data, _ := io.ReadAll(resp.Body)
		resp.Body.Close()
		if _, err := refreshModelMetrics(data); err != nil {
			log.Printf("ERROR parsing /api/ps response at startup: %v", err)
		}
	}

	requestOverrides, err := parseRequestOverrides()
	if err != nil {
		log.Fatalf("Invalid request override configuration: %v", err)
	}
	requestDefaults, err := parseRequestDefaults()
	if err != nil {
		log.Fatalf("Invalid request default configuration: %v", err)
	}

	// Start HTTP server
	listenAddr := ":" + port
	log.Printf("Listening on %s", listenAddr)
	log.Fatal(http.ListenAndServe(listenAddr, newMuxWithConfig(upstreamAddr, proxyConfig{
		requestDefaults:       requestDefaults,
		requestOverrides:      requestOverrides,
		sanitizeUTF8Responses: sanitizeUTF8ResponsesEnabled(),
		promoteReasoning:      promoteReasoningToContentEnabled(),
	})))
}
